### ISSUE TITLE
Filteren op categorie functie

### ISSUE THREAD

**Issue by itsValyria** [fdnd-agency/avl#26]
In het filter kun je categorieën selecteren. Laat allen maar de webinars/contourings zien die deze categorieën hebben.

Issue # moet all af zijn dan kun je namelijk het filter component gebruiken.

- [x] Als je op een categorie klikt laat je alleen maar cards met die categorie zien.

**Comment by Ryank2004** [comment]
Check hier de PR voor deze issue:

https://github.com/itsValyria/Oncollaboration/pull/5
