### ISSUE TITLE
Performance test

### ISSUE THREAD

**Issue by zoepje** [fdnd-agency/avl#46]

**Comment by DamianR2004** [comment]
# Fix Phase

## Lay-out shifts 

Als eerste heb ik de layout-shifts aangepakt. Het probleem trad op dat de webinars al bewogen voordat de pagina volledig ingeladen is, dit kan vervelend zijn omdat de gebruiker al eerder wilt klikken en dan een verkeerde link aanklikt.

Ik heb voor alle thumbnails automatisch een waarde ingesteld van: height = 384 en width = 384.
Dit zorgt ervoor dat de browser al van tevoren weet waar de images moeten staan en treedt dit niet meer op.

Zie deze commit:

https://github.com/itsValyria/Oncollaboration/commit/10bc70d91b462819b816360a5dc7cb5d17a0b45b#diff-eb48e8d1418a2ac9e2dbc3f030584977a1512733d099cb07e5c9a080ed610f9eL11

## Image load size

Ook kregen de images uit de database niet standaard een formaat mee. Hierdoor werden deze volledig en erg langzaam ingeladen. Gelukkig heeft directus een standaard lijn code die je kan gebruiken in het img tag. Dit zorgt ervoor dat je al een standaard groote kan aanleveren. Ook heb ik een format van avif aangevraagd, zo worden de images nog sneller ingeladen.

Zie commit hieronder:

https://github.com/itsValyria/Oncollaboration/commit/10bc70d91b462819b816360a5dc7cb5d17a0b45b#diff-eb48e8d1418a2ac9e2dbc3f030584977a1512733d099cb07e5c9a080ed610f9eL17

## Resultaten

Nadat deze dingen zijn aangepast zijn de lay-out shift errors weg en is de performance verbeterd. Deze staat nu op **88**

**Comment by DamianR2004** [comment]
# FIX PHASE 2

## Font update performance

Uit de test bleek ook nog dat de font zowel lay-out shifts als een drop in performance veroorzaakt. Dit komt onder andere omdat dit via google fonts wordt ingeladen. 

Het eerste wat ik op internet zag was [dit artikel](https://simonhearne.com/2021/layout-shifts-webfonts/) over hetzelfde probleem als ik nu heb. Ik heb nu font-display: optional toegevoegd.

Tenslotte heb ik ook nog het ttf bestand omgezet naar WOFF2, dit zorgt voor een nog betere compressie.

## Resultaten

Nadat alles is toegevoegd kom ik in totaal op een score van **97** uit. Dit is al een hele verbetering.

<img width="1421" alt="Scherm­afbeelding 2024-11-27 om 16 08 20" src="https://github.com/user-attachments/assets/bf0281f2-5157-4342-b059-c70a7019a285">


## Nog toevoegen 

In de network test is te zien dat er een object failed om in te laden, deze veroorzaakt waarschijnlijk een kleine lay-out shift. Vandaar dat de score hobbelt tussen de 100 en 91.
