### ISSUE TITLE
Codebase: check of de media queries consistent zijn

### ISSUE THREAD

**Issue by zoepje** [fdnd-agency/avl#53]

**Comment by itsValyria** [comment]
### Differences found

I found that we used some different media queries, mostly that some of us used ```screen and``` and others did not. I decided to add ```screen and``` 

```css
// with screen and
@media screen and (min-width: 1080px) {
  // css goes here...
}

// without screen and
@media (min-width: 600px) {
  // css goes here...
}
```

### How did we fix it

I decided to change all media queries to be ```screen and (min-width: XXpx)```
